export interface GlossaryTerm {
  en: string;
  de: string;
  definition: string;
}

export const GLOSSARY: GlossaryTerm[] = [
  { en: "SKU (Stock Keeping Unit)", de: "Lagerhaltungseinheit", definition: "A unique identifier for each distinct product and service that can be purchased." },
  { en: "ERP (Enterprise Resource Planning)", de: "Unternehmensressourcenplanung", definition: "Software that manages core business processes like accounting, inventory, and sales." },
  { en: "SCM (Supply Chain Management)", de: "Lieferkettenmanagement", definition: "The management of the flow of goods and services, including all processes that transform raw materials into final products." },
  { en: "Fulfillment", de: "Versandabwicklung", definition: "The process of receiving, packaging, and shipping orders for customers." },
  { en: "Credit Memo", de: "Gutschrift", definition: "A document issued by a seller to a buyer, reducing the amount that the buyer owes the seller under the terms of an earlier invoice." },
  { en: "Invoice", de: "Rechnung", definition: "A commercial document that itemizes and records a transaction between a buyer and a seller." },
  { en: "Delivery Note", de: "Lieferschein", definition: "A document accompanying a shipment of goods that lists the description, and quantity of the goods delivered." },
  { en: "Stock Buffer", de: "Lagerpuffer", definition: "A small quantity of stock kept on hand to protect against stockouts caused by fluctuations in demand or supply." },
  { en: "Matrix Product", de: "Matrixprodukt", definition: "A product with multiple variations (e.g., size, color) managed under a single umbrella article in Xentral." },
  { en: "Bundle", de: "Bündel / Set", definition: "A group of individual products sold together as a single unit." },
  { en: "Refund", de: "Rückerstattung", definition: "A repayment of a sum of money, typically to a dissatisfied customer." },
  { en: "Return (Retoure)", de: "Retoure", definition: "The process of a customer sending a product back to the retailer." },
  { en: "Master Data", de: "Stammdaten", definition: "The core data that is essential to operations in a specific business or business unit." },
  { en: "EAN (European Article Number)", de: "Europäische Artikelnummer", definition: "A standard barcode used in global trade to identify a specific retail product type." },
  { en: "Tariff Number", de: "Zolltarifnummer", definition: "A code used to classify products for customs and international trade purposes." },
  { en: "Tax Rate", de: "Steuersatz", definition: "The percentage at which an individual or corporation is taxed." },
  { en: "API (Application Programming Interface)", de: "Schnittstelle", definition: "A set of rules that allows different software applications to communicate with each other." },
  { en: "Synchronization", de: "Synchronisierung", definition: "The process of ensuring that data in two or more locations is identical." },
  { en: "Connector", de: "Konnektor", definition: "A software component that links Xentral to external platforms like Shopify." },
  { en: "Order Flow", de: "Bestellfluss", definition: "The sequence of steps an order takes from placement to delivery." },
  { en: "Tracking Number", de: "Sendungsverfolgungsnummer", definition: "A unique ID assigned to a package to monitor its movement during shipping." },
  { en: "B2B (Business-to-Business)", de: "Geschäftskundenbereich", definition: "Transactions or business conducted between one business and another." },
  { en: "B2C (Business-to-Consumer)", de: "Privatkundenbereich", definition: "Transactions or business conducted directly between a company and consumers." },
  { en: "Influencer Budget", de: "Influencer-Budget", definition: "Funds allocated for marketing through social media influencers." },
  { en: "Gift Card", de: "Gutschein", definition: "A prepaid stored-value money card issued by a retailer to be used as an alternative to cash." },
  { en: "Accounting", de: "Buchhaltung", definition: "The process of recording, summarizing, and analyzing financial transactions." },
  { en: "Payment Method", de: "Zahlungsart", definition: "The way a customer chooses to pay for their order (e.g., PayPal, Credit Card)." },
  { en: "Tiered Discount", de: "Staffelrabatt", definition: "A discount structure where the price per unit decreases as the quantity purchased increases." },
  { en: "Manual Order", de: "Manuelle Bestellung", definition: "An order created directly in the ERP system by a staff member rather than automatically via a webshop." },
  { en: "Safety Stock", de: "Sicherheitsbestand", definition: "Extra inventory kept to prevent stockouts during unexpected demand or supply delays." },
  { en: "Article Number", de: "Artikelnummer", definition: "A unique number assigned to a product for identification." },
  { en: "Variant", de: "Variante", definition: "A specific version of a product (e.g., Size M, Color Blue)." },
  { en: "Inventory", de: "Lagerbestand", definition: "The quantity of goods and materials on hand." },
  { en: "Shipment Confirmation", de: "Versandbestätigung", definition: "An email or notification sent to a customer when their order has been shipped." },
  { en: "Lead Developer", de: "Leitender Entwickler", definition: "The person responsible for the technical direction and implementation of a project." },
  { en: "ERP System", de: "ERP-System", definition: "A suite of integrated applications used to manage business data." },
  { en: "Shopify", de: "Shopify", definition: "An e-commerce platform used to create and manage online stores." },
  { en: "Klaviyo", de: "Klaviyo", definition: "A marketing automation platform often used for e-commerce emails." },
  { en: "Pallet", de: "Palette", definition: "A flat transport structure that supports goods in a stable fashion while being lifted by a forklift." },
  { en: "Credit Note", de: "Gutschriftanzeige", definition: "A document sent by a seller to a buyer to notify them that their account has been credited." },
  { en: "Position", de: "Position", definition: "An individual line item in an order or invoice." },
  { en: "Material Control", de: "Materialkontrolle", definition: "The process of managing and tracking materials used in production or sales." },
  { en: "Refund Process", de: "Erstattungsprozess", definition: "The steps taken to return money to a customer." },
  { en: "Return Management", de: "Retourenmanagement", definition: "The handling of returned goods from customers." },
  { en: "Sync Interval", de: "Synchronisierungsintervall", definition: "The frequency at which data is updated between systems (e.g., every 15 minutes)." },
  { en: "Tax Rate", de: "Steuersatz", definition: "The percentage of tax applied to a product or service." },
  { en: "Master Data Management", de: "Stammdatenverwaltung", definition: "The discipline of managing the core data of an organization." },
  { en: "Stock Update", de: "Bestandsaktualisierung", definition: "The process of updating the quantity of items in stock." },
  { en: "Fulfillment Partner", de: "Versandpartner", definition: "A third-party company that handles storage and shipping for a retailer." },
  { en: "Order Status", de: "Bestellstatus", definition: "The current stage of an order (e.g., Pending, Shipped, Cancelled)." }
];
